tap "AdoptOpenJDK/openjdk"
tap "homebrew/cask-fonts"

brew "awscli"
brew "bat"
brew "git"
brew "git-delta"
brew "mackup"
brew "shellcheck"
brew "starship"
brew "tmux"
brew "yarn"

cask "adoptopenjdk8"
cask "docker"
cask "dropbox"
cask "firefox"
cask "font-fira-code"
cask "insomnia"
cask "iterm2"
cask "rectangle"
cask "signal"
cask "visual-studio-code"
